# Generated by Django 5.0 on 2025-05-10 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learninglog',
            old_name='explaination',
            new_name='explanation',
        ),
    ]
