# Generated by Django 5.0 on 2025-05-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_rename_explaination_learninglog_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='learninglog',
            name='quiz',
            field=models.TextField(blank=True, null=True),
        ),
    ]
