# Generated by Django 5.0 on 2025-05-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0003_learninglog_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='learninglog',
            name='user_answers',
            field=models.TextField(blank=True, null=True),
        ),
    ]
