# Generated by Django 5.2.1 on 2025-11-12 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0004_learninglog_user_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learninglog',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutor.studentprofile'),
        ),
    ]
